#!/bin/sh

google() {
	browser='user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36'
	curl "https://www.google.com/search" \
		-s -G --data-urlencode "q=$1" \
		-H "$browser" \
		--compressed 
}

data="$(google "$* quotes")"

spell="$(printf "%s" "$data" |  pup 'div#taw > div > p > a:first-of-type text{}' | tr -d '\n' | recode html..utf8 )"

qoutes="$(printf "%s" "$data" |  pup 'div[data-mh="-1"] i text{}' | recode html..utf8 | sed 's/^/* /' )"

[ -z "$spell" ] || printf "Did you mean %s ?\n" "$spell"

[ -z "$qoutes" ] && printf "No qoutes found\n" || printf "%s\n" "$qoutes"
